unnixdev_leaveonline/LeaveOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('frontend.urls')), # new
    path('api/', include('apileaveonline.urls')), # new
    path('line/', include('lineapp.urls')), # new
    
    # path('account/', include('account.urls')), # new

    url(r'^account/', include('allauth.urls')),
]

unnixdev_leaveonline/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    # path('', views.index, name='index'),

    # path('signup/', views.register, name='signup'),
    # path('signupPage/', views.registerPage, name="signuppage"),

    path('signin/', views.login, name='signin'),
    path('signout/', views.logout, name='signout'),

    path('signupLinePage/', views.registerLinePage, name="signuplinepage"),
    path('signupLine/', views.registerLine, name="signupLine")
]

unnixdev_leaveonline/frontend/urls.py
from django.urls import path

from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.IndexPage, name='index'),
    # path('checkSend', views.checkSendForm, name='checkSend')

]

unnixdev_leaveonline/frontend/models.py
from django.db import models

# Create your models here.

unnixdev_leaveonline/frontend/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.models import User
# Create your views here.

from django.http import JsonResponse

from users import models

import json

from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

def sessionResult(request):
    json_auth = {
        "userpk": None,
        "status_login" : False,
        "user" : None,
        "email" : None,
    }
    if request.session.keys():
        user_id = request.session['_auth_user_id']
        user_obj = User.objects.get(pk=user_id)
        json_auth["userpk"] = user_id
        json_auth['user'] = user_obj.username
        json_auth['email'] = user_obj.email
        json_auth["status_login"] = True

        return json_auth


    else: 
        return json_auth

def IndexPage(request):
    jsonSess = sessionResult(request)
    if(jsonSess["status_login"] == False):
        return redirect('/account/login/')
    isSuper = False
    
    temp = models.Profile.objects.filter(user = jsonSess["userpk"])
    depName = ""
    posName = ""
    for val in temp:
        depName = val.dep_name
        posName = val.pos_name
    
    if(models.Suppervisor.objects.filter(sup_name = jsonSess["userpk"]).values()):
        isSuper = True

    return render(request, 'frontend_html/index.html', {"auth_":jsonSess, "isSuper": isSuper, "depName":depName, "posName":posName})

unnixdev_leaveonline/frontend/templates/base/base_page.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Unixdev Leave Online</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% comment %} <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet"> {% endcomment %}
    <link href="https://fonts.googleapis.com/css?family=Prompt&display=swap" rel="stylesheet">
    
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src={% static 'config.js' %}></script>
  </head>

  <body>
      <div class="balckground_opa googleS" style="">
      </div>
      
      <div class="balckground_approve" style="">
        <img src="{% static "img/Double Ring-1.4s-130px.gif" %}">
      </div>

      <div class="balckground_detail detailFade" style="">
      </div>
      

      <div class="content_detail_modal">
        
        <div  class="content_detail">
        <div>
          <img class="close-modal" style="width: 5%; float: right;" src="{% static "img/cross_test.png" %}">
        </div>
          <h1>รายระเอียด</h1>
          <div style="width:50%; margin:10px auto; " id="barchart"></div>
          <div class="content_ddd"></div>
        </div>
      </div>
      <div style="z-index:10 ;display: none; " class="content_detail detailFadeTest">  
          <h1>รายระเอียด</h1>
          <div style="width:50%; margin:10px auto; " id="barchart"></div>
          <div class="content_ddd"></div>
      </div>
      

      <div style="">
        <div class="header">
          <div class="braner">
            <h1><a href="{% url 'frontend:index' %}"><span style="color:orange;">Unix</span><span style="color:black;">Dev</span></a></h1>
          </div>
          <div class="user_auth">
            {% if auth_.status_login %}
              <p>
                ชื่อผู้ใช้งาน : <span pkid="{{auth_.userpk}}" id="username_">{{auth_.user}}</span>
                แผนก : <span id="department_">{{depName}}</span>
                ตำแหน่ง : <span id="position_">{{posName}}</span>
                <a href="{% url 'account:signout' %}">ออกจากระบบ</a>
              <p>
            {% else %}
              
              <a href="{% url 'account:signin' %}">เข้าสู่ระบบ</a>
            {% endif %}
          </div>
          
        </div>
        {% comment %} <hr> {% endcomment %}
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>

        
        {% comment %} <hr style="clear: both;"> {% endcomment %}
        {% comment %} Footer
        <div class="user_info">
          {% if auth_.status_login %}
            <p>
              User : <span pkid="{{auth_.userpk}}" id="username_">{{auth_.user}}</span> <br>
              Department : <span id="department_">{{depName}}</span> <br> 
              Position : <span id="position_">{{posName}}</span> <br>
            <p>
          {% endif %}
        
        </div> {% endcomment %}
    </div>
  </body>

</html>

unnixdev_leaveonline/frontend/templates/base/base_page_regis.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% comment %} <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet"> {% endcomment %}
    <link href="https://fonts.googleapis.com/css?family=Prompt&display=swap" rel="stylesheet">
  
    {% load static %}

    <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src={% static 'config.js' %}></script>
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>

  <body>
      
      <div class="balckground_opa googleS" style="">
      </div>
      
      <div class="balckground_approve" style="">
        <img src="{% static "img/Double Ring-1.4s-130px.gif" %}">
      </div>

      <div style="">
        <div class="header">
          <div class="braner">
            <h1><a href="{% url 'frontend:index' %}"><span style="color:black">Unix</span><span>Dev</span></a></h1>
          </div>

          
        </div>
        {% comment %} <hr> {% endcomment %}
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>

    </div>
  </body>

</html>